config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'tags/:tag', to: 'links#tag', as: "tag"
	
	resources :charges
	
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"

    end
  end

  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end

  resources :comments, :only => [:create, :destroy]

  root to: 'links#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Commentable
  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  acts_as_votable
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, :as => :commentable
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  include Commentable
  require 'uri'
  

  belongs_to :user
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings
  acts_as_votable

  validates :url, :format => {:with => URI.regexp}
  
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).links
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings
  has_many :links, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :link
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password) }
          devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_name, :email, :password, :current_password,) }
      end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def index
  end

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
     :email => 'chidoro9@yahoo.com',
     :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # def create
  #   @link = Link.find(params[:link_id])
  #   @comment = @link.comments.build(comment_params.merge(:user => current_user))

  #   if @comment.save
  #     redirect_to @link, notice: "Comment successful."  
  #   else
  #     render new, notice: "Comment failed"
  #   end
  # end

  # def destroy
  #   @comment = Comment.find(params[:id])
  #   @comment.destroy
  #   redirect_to @link, notice: "Comment deleted"
  # end

  # private

  # def comment_params
  #   params.require(:comment).permit(:commentable_id, :commentable_type, :body)
  # end

  # # Use callbacks to share common setup or constraints between actions.
  # def set_link
  #   @link = Link.find(params[:id])
  # end


  def create
    current_user.comments.create(comment_params)
    redirect_to :back, :notice => "Added Comment"
  end

  def destroy
    current_user.comments.destroy(params[:id])
    redirect_to :back, :notice => "Removed Comment"
  end

  def upvote
    @comment = Comment.find(params[:id])
    @comment.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_by current_user
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :body)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @links = Link.order("cached_votes_up DESC").page(params[:page])
  end

  def show
  end

  def tag
    @links = Link.tagged_with(params[:tag])
  end
  
  def new
    @link = current_user.links.build
  end
  
  def edit
  end
  
  def create
    @link = current_user.links.build(link_params)
    
    if @link.save
      redirect_to @link, notice: 'Link was successfully created.'
    else
      render :new 
    end
  end
  
  def update
    if @link.update(link_params) 
      redirect_to @link, notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end
  
  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :all_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_comments(commentable, nested = false)
    render :partial => 'comments/index', :locals => { :commentable => commentable, :nested => nested }
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end
end

app/views/comments/_index.html.erb
<% unless nested %><h3>Comments</h3><% end %>

<table class="table">
  <% if nested %>
    <tr class='collapse' id='comments_for_<%= dom_id commentable %>'>
      <td colspan="3">
        <%= form_for(commentable.comments.new, html: {class: "form-horizontal", role: "form"}) do |f| %>
          <%= f.hidden_field :commentable_type %>
          <%= f.hidden_field :commentable_id %>
           <div class="form-group">
            <%= f.label :body, 'Reply', class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_area :body, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10"><%= f.submit class: "btn btn-primary" %></div>
          </div>
        <% end %>
      </td>
    </tr>
  <% end %>
  <%- commentable.comments.reload.each do |comment| %>
    <tr>
      <td>
        <p><%= comment.body %></p>
        <%=  %>
        <h5><em>by</em> <%= comment.user.user_name %> <small>at <%= comment.created_at.strftime (" %I %M %P") %></small>
          <a data-toggle="collapse" data-target="#comments_for_<%= dom_id comment %>" aria-expanded="false" aria-controls="#viewdetails">Reply &raquo;</button>
        </h5>
      </td>
      <td>
        <% unless nested %>
        <div class="votes-container">
          <%= link_to like_comment_path(comment), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
            Upvote
            <%= comment.get_upvotes.size %>
          <% end %>
          <%= link_to dislike_comment_path(comment), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-down"></span>
            Downvote
            <%= comment.get_downvotes.size %>
          <% end %>
        </div>
        <% end %>
      </td>
    </tr>
    <tr class="nested">
      <td colspan="3">
        <%= render_comments(comment, true) %>
      </td>
    </tr>
  <% end %>
  <% unless nested %>
  <tr>
    <td colspan="3">
      <%= form_for(commentable.comments.new, html: {class: "form-horizontal", role: "form"}) do |f| %>
        <%= f.hidden_field :commentable_type %>
        <%= f.hidden_field :commentable_id %>
         <div class="form-group">
          <%= f.label :body, 'Reply', class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_area :body, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10"><%= f.submit class: "btn btn-primary" %></div>
        </div>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TBD</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div id="logo" class="navbar-brand"><{•̃̾_•̃̾}> <%= link_to "TBD", root_path %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <% if user_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <li><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span></li>
			  <li>
				<%= form_tag charges_path do %>
				  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
				          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
				          data-description="A Donation"
				  		  data-label="Donate"
				          data-amount="500"></script>
				<% end %>
			  </li>
              <li><%= link_to 'Submit link', new_link_path %></li>
              <li><%= link_to 'Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
        <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
            
        <% end -%>
      </nav>
    </div>
  </div>
</header>

<div id="main_content" class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>

  <div id="content" class="col-md-9 center-block">
    <%= yield %>
  </div>
</div>
</div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.text_field :all_tags, placeholder: 'Tags separated by commas.' %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-lg btn-primary"  %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<div class="row">
  <% @links.each do |link| %>
      <div class="link row clearfix">
        <div class="col-lg-6">
          <h2>
            <%= link_to link.title, url_for(link.url) %><br>
            <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> ago
              by <%= link.user.user_name %></small>
          </h2>
        </div>
        <div class="col-lg-6">
          <% image_ex = [".jpg", ".png", ".gif", ".jpeg"] %>
          <% if image_ex.any? { |ext| link.url.include? ext } %>
              <%= image_tag link.url, :class => "img-responsive", :style => "max-height:70px;" %>
          <% else %>
              <p><%= link_to url_for(link.url) %></p>
          <% end %>
        </div>
        <h4 class="all_tags"><%=raw tag_links(link.all_tags) %></h4>
      </div>

      <div class="btn-group">
        <a class="btn btn-default btn-sm" href="<%= link_path(link.id) %>">Comments</a>
        <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
            Upvote
            <%= link.get_upvotes.size %>
        <% end %>

        <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-down"></span>
            Downvote
              <%= link.get_downvotes.size %>
        <% end %>
      </div>

  <% end %>
  <div class="link row clearfix">
    <%= paginate @links %>
  </div>
</div>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <p id="notice"><%= notice %></p>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <h2><strong>Title:</strong><%= @link.title %></h2>
  </div>
  <div class="col-lg-6">
   <% image_ex = [".jpg", ".png", ".gif", ".jpeg"] %>
          <% if image_ex.any? { |ext| @link.url.include? ext } %>
              <%= image_tag @link.url, :class => "img-responsive", :style => "max-height:70px;" %>
          <% else %>
              <p><%= link_to url_for(@link.url) %></p>
          <% end %>
  </div>
</div>

<div class="row">
  <%= render_comments(@link) %>
</div>
    

app/views/links/tag.html.erb
<h2>An index of similarly tagged <%= @tag.try(:name) %></h2>

  <% @links.each do |link| %>

    <div class="row">
      <div class="col-lg-12">
        <p id="notice"><%= notice %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <h2><strong>Title:</strong><%= link.title %></h2>
      </div>
      <div class="col-lg-6">
       <% image_ex = [".jpg", ".png", ".gif", ".jpeg"] %>
          <% if image_ex.any? { |ext| link.url.include? ext } %>
              <%= image_tag link.url, :class => "img-responsive", :style => "max-height:70px;" %>
          <% else %>
              <p><%= link_to url_for(link.url) %></p>
          <% end %>
      </div>
    </div>

    <div class="row">
      <%= render_comments(link) %>
    </div>
  <% end %>